name: Auto Increment and Publish

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/**'
      - 'docs/**'
  
  workflow_dispatch:
    inputs:
      publish_npm:
        description: 'Publish to NPM?'
        required: true
        default: true
        type: boolean

jobs:
  auto-increment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: |
          npm run cjs_test
          npm run esm_test

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Increment Version
        id: version
        run: |
          OLD_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $OLD_VERSION"
          
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
          
          echo "Version incremented: $OLD_VERSION -> $NEW_VERSION"
          
          npm install --package-lock-only
          
          git add package.json package-lock.json
          git commit -m "Auto increment to v$NEW_VERSION"
          git tag "v$NEW_VERSION"

      - name: Push Changes
        run: |
          git push origin HEAD:${{ github.ref_name }}
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish to NPM
        if: |
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_npm == 'true')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          release_name: Release v${{ steps.version.outputs.new_version }}
          body: |
            ## What's Changed
            
            - Version incremented from ${{ steps.version.outputs.old_version }} to ${{ steps.version.outputs.new_version }}
            - All tests passing
            - Ready for production use
            
            ## Installation
            
            ```bash
            npm install brave-real-browser@${{ steps.version.outputs.new_version }}
            ```
            
            ## Usage
            
            ```javascript
            const { connect } = require('brave-real-browser');
            
            const { browser, page } = await connect({
              headless: false,
              turnstile: true
            });
            ```
          draft: false
          prerelease: false

      - name: Summary
        if: always()
        run: |
          echo "## Workflow Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Field | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Package | brave-real-browser |" >> $GITHUB_STEP_SUMMARY
          echo "| Old Version | ${{ steps.version.outputs.old_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| New Version | ${{ steps.version.outputs.new_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Trigger | ${{ github.event_name }} |" >> $GITHUB_STEP_SUMMARY